### ISSUE TITLE
Sega Genesis xml is missing

### ISSUE THREAD

**Issue by ryuuji89** [billyc999/Game-database-info#5]
Sega Genesis xml is missing. 
(if it is not done let me know maybe I can help)

**Comment by billyc999** [comment]
ive got 189 csv files now, sega genesis is done . I've passed to TeeDub to check and upload them. not heard from him yet..

**Comment by billyc999** [comment]
ive got 189 csv files now, sega genesis is done . I've passed to TeeDub to check and upload them. not heard from him yet.. 
still waiting for the psp one back also  from frankyrizzo on hs forums, ive got a copy without descriptions , but he as added them so would be better to upload that version.

ill probably upload all the files shortly , then they can be replaced/ or reverted if needed
